# Docker Compose file for development
version: "2"
services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../data/replication_packets:/data/replication_packets
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
      - mail

  mail:
    build:
      context: ./postfix/
      dockerfile: Dockerfile
    environment:
      MAILDOMAIN: metabrainz.org
    ports:
      - "25:25"

  db:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: metabrainz
      POSTGRES_PASSWORD: metabrainz
      POSTGRES_DB: metabrainz

  redis:
    image: redis:3.2.1
