# Docker Compose file for production
version: "2"
services:

  nginx:
    restart: always
    build:
      context: ./nginx_custom/
      dockerfile: Dockerfile
    volumes:
      - ../data/replication_packets:/var/www/metabrainz.org/replication_packets
    links:
      - web
    ports:
      - "80:80"

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    volumes:
      - ../data/replication_packets:/data/replication_packets
    ports:
      - "3031:3031"
    depends_on:
      - db
      - redis

  mail:
    build:
      context: ./postfix/
      dockerfile: Dockerfile
    environment:
      MAILDOMAIN: metabrainz.org
    ports:
      - "25:25"

  db:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: metabrainz
      POSTGRES_PASSWORD: metabrainz
      POSTGRES_DB: metabrainz

  redis:
    image: redis:3.2.1
